### ISSUE TITLE
Prebuilt image uses "localhost" redirection when logging

### ISSUE THREAD

**Issue by Elspan** [calcom/docker#396] opened 2024-12-02 19:51 UTC
Hello,

If you use the "calcom/cal.com" image from Docker Hub, even after changing the NEXT_PUBLIC_WEBAPP_URL and NEXT_PUBLIC_API_V2_URL, the app redirects to "localhost" when authenticating a user. Other pages in the app are not affected. This is not a caching issue, as I tested with the cache disabled in the browser, cleared the database, etc.

Edit : The "view public page" link points to localhost:3000, and the username prefix are also "localhost:3000"
After testing with older images the issue seems to be on the :main image.

**Comment by tigerblue77** [comment] 2024-12-03 21:32
Duplicate of https://github.com/calcom/docker/issues/319

**Closed** 2024-12-05 15:21 UTC
