### ISSUE TITLE
@calcom/lib not found

### ISSUE THREAD

**Issue by kettenbach-it** [calcom/docker#92] opened 2022-02-24 08:06 UTC
yarn install failes:

```
#11 1.256 error An unexpected error occurred: "https://registry.yarnpkg.com/@calcom%2flib: Not found".
```

**Comment by afroeagle** [comment] 2022-02-27 18:32
This appears to be a duplicate of https://github.com/calcom/docker/issues/85.

**Comment by BahrouniYousra** [comment] 2022-03-09 09:27
Same issue here, have you find a solution plz !

**Comment by agustif** [comment] 2022-03-09 12:04
The problem here seems that the docker setup tries to install the package @calcom/lib as it was a regular published in npm/yarn package, which is not.

@calcom/lib lives in calcom/packages/lib now. And it should be picked up during install of the monorepo/turborepo, hope this can find you debug the problem.

**Comment by secfigo** [comment] 2022-03-21 04:49
Please follow the instructions available in this PR to resolve this. 

https://github.com/calcom/docker/pull/86#issuecomment-1047179700 

I will summarize the steps here for your convenience. 

```
git clone --recursive https://github.com/calendso/docker.git calendso-docker
cd calendso-docker/
git remote add searsaw https://github.com/searsaw/docker.git
git fetch --all
git checkout searsaw/fix-workspaces-build-issues
git submodule update --init --recursive
mv .env.example .env
docker-compose up --build -d
```

You will have to visit localhost:5555 afterward to set up the user(s). Reason? See below.  

<img width="677" alt="image" src="https://user-images.githubusercontent.com/11695998/159206791-e61be1f8-1c2f-4072-9ecd-c586bac37343.png">


The password has to be generated using bcrypt. Which you can generate for testing purposes using the below app.

https://bcrypt-generator.com/

**Comment by AmoghSaxena** [comment] 2022-03-23 13:45
> Please follow the instructions available in this PR to resolve this.
> 
> [#86 (comment)](https://github.com/calcom/docker/pull/86#issuecomment-1047179700)
> 
> I will summarize the steps here for your convenience.
> 
> ```
> git clone --recursive https://github.com/calendso/docker.git calendso-docker
> cd calendso-docker/
> git remote add searsaw https://github.com/searsaw/docker.git
> git fetch --all
> git checkout searsaw/fix-workspaces-build-issues
> git submodule update --init --recursive
> mv .env.example .env
> docker-compose up --build -d
> ```
> 
> You will have to visit localhost:5555 afterward to set up the user(s). Reason? See below.
> 
> <img alt="image" width="677" src="https://user-images.githubusercontent.com/11695998/159206791-e61be1f8-1c2f-4072-9ecd-c586bac37343.png">
> 
> The password has to be generated using bcrypt. Which you can generate for testing purposes using the below app.
> 
> https://bcrypt-generator.com/

Completly Agree with this solution. I had the same problem but got fixed by  [#86 Comment](https://github.com/calcom/docker/pull/86#issuecomment-1047179700)

**Comment by krumware** [comment] 2022-04-04 15:45
Submodule update is knocked out, and may have created some other issues now that we aren't one month behind anymore

**Comment by krumware** [comment] 2022-04-29 19:54
resolves with latest

**Closed by krumware** 2022-04-29 19:54 UTC
